import type { Drink } from "./types";
import { slugify } from "./slugify";

// Notion 연동 전 미리보기 및 개발용 목 데이터.
// drink_menu 원본 중 사케 / 소츄 / 전통주 항목만 옮겨왔다 (잔음료, 리큐어 제외).
const raw: Omit<Drink, "slug">[] = [
  // 전통주
  {
    name: "동해 소주",
    category: "전통주",
    abv: "17.5도",
    price: "8,000원",
    description: "군더더기 없이 소주다운 소주",
    sortOrder: 0,
  },
  {
    name: "황금 보리",
    category: "전통주",
    abv: "17도",
    price: "13,000원",
    description: "약간의 단맛이 부드럽게 넘어가 부담없이 마시기 좋은",
    sortOrder: 1,
  },
  {
    name: "고흥 유자주",
    category: "전통주",
    abv: "8도",
    price: "24,000원",
    description: "전남 고흥의 유자를 담아 상큼함. 낮은 도수로 술보다 음료에 가까운 기분.",
    sortOrder: 2,
  },

  // 사케 - 잔 (90ml 잔 / 270ml 도쿠리)
  {
    name: "카와츠루 사누키 클라우디",
    category: "사케",
    type: "잔",
    price: "9,000원 / 25,000원",
    sortOrder: 3,
  },
  {
    name: "사라 준마이긴죠",
    category: "사케",
    type: "잔",
    price: "12,000원 / 34,000원",
    sortOrder: 4,
  },
  {
    name: "시치스이 준마이긴죠 55 오마치",
    category: "사케",
    type: "잔",
    price: "13,000원 / 36,000원",
    sortOrder: 5,
  },

  // 사케 - 병
  {
    name: "요이유메",
    category: "사케",
    type: "병",
    price: "49,000원",
    description: "쌀을 곱게 갈아 만든 크림 같은 술",
    tastingNotes: "달큰하고 부드러워 입문용으로 추천",
    sortOrder: 6,
  },
  {
    name: "사라 준마이긴죠",
    category: "사케",
    type: "병",
    price: "75,000원",
    description: "차가운 물처럼 투명해",
    tastingNotes: "자기주장보단 음식의 맛을 조용히 받쳐주는",
    sortOrder: 7,
  },
  {
    name: "반슈잇콘 준마이 나츠카라 (여름한정주)",
    category: "사케",
    type: "병",
    price: "78,000원",
    description: "여름 저녁 바람처럼 시원하게 떨어지는 술",
    tastingNotes: "단맛은 짧고 산미는 또렷해 기름진 안주와 추천",
    pairing: "기름진 안주",
    sortOrder: 8,
    limitedEdition: true,
  },
  {
    name: "니토 준마이 반자이 70 나마자케",
    category: "사케",
    type: "병 · 생주",
    price: "80,000원",
    description: "풋풋한 향과 촉촉한 쌀맛",
    tastingNotes: "막 짜낸 쌀의 생기가 느껴지는 생주",
    sortOrder: 9,
  },
  {
    name: "야마노고토부키 프릭스 1",
    category: "사케",
    type: "병",
    price: "80,000원",
    description: "잔잔한 탄산감에 산미가 또렷한",
    tastingNotes: "분홍빛 라벨처럼 경쾌하고 장난스러운",
    sortOrder: 10,
  },
  {
    name: "야마노고토부키 오마치 13",
    category: "사케",
    type: "병",
    price: "80,000원",
    description: "튀지 않지만 맛의 중심이 있어",
    tastingNotes: "식사와 함께 천천히 마시기 좋은",
    sortOrder: 11,
  },
  {
    name: "카와츠루 사누키 클라우디",
    category: "사케",
    type: "병 · 니고리",
    abv: "6도",
    price: "70,000원",
    description: "막걸리를 닮은 포근한 질감",
    tastingNotes: "가벼운 도수로 편하게 마시기 좋은 니고리",
    sortOrder: 12,
  },
  {
    name: "시치스이 준마이긴죠 55 오마치",
    category: "사케",
    type: "병",
    price: "82,000원",
    description: "멜론과 배를 닮은 화사한 과실향",
    tastingNotes: "지나치게 달지 않아 첫 병으로 추천",
    sortOrder: 13,
  },
  {
    name: "아카부 준마이",
    category: "사케",
    type: "병",
    price: "83,000원",
    description: "물맛 좋은 곳에서 빚은 맑은 친구",
    tastingNotes: "두고두고 생각나는 감칠맛",
    sortOrder: 14,
  },
  {
    name: "쿠로우시 준마이다이긴죠 오마치",
    category: "사케",
    type: "병",
    price: "73,000원",
    description: "향은 부드럽게 열리지만 단맛은 짧고",
    tastingNotes: "주도 +13의 선명한 드라이함이 특징",
    sortOrder: 15,
  },
  {
    name: "미요키쿠 혼죠조 나마겐슈",
    category: "사케",
    type: "병 · 생원주",
    abv: "20도",
    price: "72,000원",
    description: "기름진 음식 옆에서도 밀리지 않는",
    tastingNotes: "20도의 힘이 느껴지는 생원주",
    pairing: "기름진 음식",
    sortOrder: 16,
  },
  {
    name: "쿠라모토se",
    category: "사케",
    type: "병",
    price: "110,000원",
    description: "달게만 느껴지지 않고",
    tastingNotes: "쌀의 새콤함이 깨끗하게 살아있는",
    sortOrder: 17,
  },
  {
    name: "사와야 마츠모토 울트라",
    category: "사케",
    type: "병",
    price: "150,000원",
    description: "얇은 유리잔처럼 맑고 섬세한 결",
    tastingNotes: "차분하게 마실수록 완성도가 느껴지는",
    sortOrder: 18,
  },
  {
    name: "닷사이 블루 타입 23",
    category: "사케",
    type: "병 · 다이긴죠",
    price: "200,000원",
    description: "차갑게 닦아낸 과실 같은, 투명한 다이긴죠",
    tastingNotes: "입안을 한 번 맑게 씻어주는 듯한 섬세함",
    sortOrder: 19,
  },
  {
    name: "시치스이 준마이다이긴죠 40 키모토 brilliant",
    category: "사케",
    type: "병 · 다이긴죠",
    price: "200,000원",
    description: "산미가 부드러운 단맛을 받쳐주며",
    tastingNotes: "부드럽게 시작하지만 끝은 또렷한",
    sortOrder: 20,
  },
  {
    name: "킨스즈메 히쇼 준마이다이긴죠",
    category: "사케",
    type: "병 · 다이긴죠",
    price: "230,000원",
    description: "화려함보다 깊이감이 느껴지는 프리미엄 사케",
    tastingNotes: "쌀의 단맛, 과실향이 천천히 열려 긴 여운이 남는",
    sortOrder: 21,
  },

  // 소츄 - 고구마
  {
    name: "세키토바",
    category: "소츄",
    type: "고구마",
    price: "10,000원",
    description: "고구마 소츄의 모범생 같은 한 잔",
    sortOrder: 22,
  },
  {
    name: "세키토바 무라사키",
    category: "소츄",
    type: "고구마 (자색고구마)",
    price: "10,000원",
    description: "잘 익은 고구마 같은 달큰함",
    sortOrder: 23,
  },
  {
    name: "세키토바 말차",
    category: "소츄",
    type: "고구마",
    price: "12,000원",
    description: "고구마 단맛 뒤로 말차 특유의 쌉싸름하고 맑은 향",
    sortOrder: 24,
  },
  {
    name: "다이야메",
    category: "소츄",
    type: "고구마",
    price: "8,000원 / 900ml 80,000원",
    description: "고구마소츄 특유의 무거움보단 맑고 리치한",
    sortOrder: 25,
  },
  {
    name: "아카루이노우손 야부키타",
    category: "소츄",
    type: "고구마",
    price: "9,000원 / 720ml 90,000원",
    description: "햇살 드는 시골 마을에 말차 밭이 떠오르는 정겨운 고구마소츄",
    sortOrder: 26,
  },

  // 소츄 - 보리
  {
    name: "무기시루",
    category: "소츄",
    type: "보리",
    price: "8,000원",
    description: "우유에 말아먹는 조리퐁처럼 꼬소한",
    sortOrder: 27,
  },
  {
    name: "아카 엔마",
    category: "소츄",
    type: "보리",
    price: "8,000원 / 720ml 80,000원",
    description: "맑고 반듯하게 떨어지는 보리소츄",
    sortOrder: 28,
  },
  {
    name: "백년의고독",
    category: "소츄",
    type: "보리",
    abv: "40도",
    price: "720ml 210,000원",
    description: "떡갈나무(오크통)에 숙성해 100년의 전통이 느껴지는",
    sortOrder: 29,
  },
];

export const mockDrinks: Drink[] = raw.map((d, i) => ({
  ...d,
  slug: `${slugify(d.name)}-${i}`,
  priceSummary: d.price,
}));
